In [4]:
# class EXCHANGE():
#     XSHG = 'XSHG'
#     SSE = 'XSHG'
#     SH = 'XSHG'
#     XSHE = 'XSHE'
#     SZ = 'XSHE'
#     SZE = 'XSHE'
    
    
class EXCHANGE():
    XSHG = 'XSHG'
    SSE = 'XSHG'
    SH = 'SH'
    XSHE = 'XSHE'
    SZ = 'SZ'
    SZE = 'XSHE'

def normalize_code(symbol, pre_close=None):
    """
    归一化证券代码

    :param code 如000001
    :return 证券代码的全称 如000001.XSHE
    """
    if (not isinstance(symbol, str)):
        return symbol

    if (symbol.startswith('sz') and (len(symbol) == 8)):
        ret_normalize_code = '{}.{}'.format(symbol[2:8], EXCHANGE.SZ)
    elif (symbol.startswith('sh') and (len(symbol) == 8)):
        ret_normalize_code = '{}.{}'.format(symbol[2:8], EXCHANGE.SH)
    elif (symbol.startswith('00') and (len(symbol) == 6)):
        if ((pre_close is not None) and (pre_close > 2000)):
            # 推断是上证指数
            ret_normalize_code = '{}.{}'.format(symbol, EXCHANGE.SH)
        else:
            ret_normalize_code = '{}.{}'.format(symbol, EXCHANGE.SZ)
    elif ((symbol.startswith('399') or symbol.startswith('159') or \
        symbol.startswith('150')) and (len(symbol) == 6)):
        ret_normalize_code = '{}.{}'.format(symbol, EXCHANGE.SH)
    elif ((len(symbol) == 6) and (symbol.startswith('399') or \
        symbol.startswith('159') or symbol.startswith('150') or \
        symbol.startswith('16') or symbol.startswith('184801') or \
        symbol.startswith('201872'))):
        ret_normalize_code = '{}.{}'.format(symbol, EXCHANGE.SZ)
    elif ((len(symbol) == 6) and (symbol.startswith('50') or \
        symbol.startswith('51') or symbol.startswith('60') or \
        symbol.startswith('688') or symbol.startswith('900') or \
        (symbol == '751038'))):
        ret_normalize_code = '{}.{}'.format(symbol, EXCHANGE.SH)
    elif ((len(symbol) == 6) and (symbol[:3] in ['000', '001', '002', 
                                                 '200', '300'])):
        ret_normalize_code = '{}.{}'.format(symbol, EXCHANGE.SZ)
    else:
        #print(symbol)
        ret_normalize_code = symbol

    return ret_normalize_code
normalize_code('000651')

'000651.SZ'

In [2]:
normalize_code('sh600089')

'600089.SH'

In [5]:
#这段代码是把原来新闻csv文件中的stocks列转变成符合规则的JQ_ID形式列
import pandas as pd
import json

# 读取CSV文件
df = pd.read_csv('data_raw/新闻_20220328.csv',  encoding='utf-8')

In [6]:

#print(df.columns)
# 定义提取股票代码的函数
def extract_stock_codes(stocks_str):
    stocks_list = json.loads(stocks_str)
    stock_codes = [stock['stocks_code'][2:] for stock in stocks_list]  # 提取股票代码并去掉前缀
    return stock_codes

# 定义处理函数fun

# 对每一行应用处理函数，并将结果写入新的列中
df['JQ_ID'] = df["stocks"].apply(extract_stock_codes)
df['JQ_ID'] = df['JQ_ID'].apply(lambda x: list(map(normalize_code, x)))
# 将结果写入新的CSV文件
print(df.columns)
#df.to_csv('data_processed/新闻_20220328_JQ_ID.csv', index=False)

print("处理完成，新的CSV文件已保存。")

Index(['Unnamed: 0', 'id', 'title', 'content', 'stocks', 'new_date_column',
       '宏观', '概念', '行业', '公司', '财务', 'JQ_ID'],
      dtype='object')
处理完成，新的CSV文件已保存。

In [47]:
pd.read_csv("data_processed/新闻_20220328_JQ_ID.csv")

,Unnamed: 0,id,title,content,stocks,new_date_column,宏观,概念,行业,公司,财务,JQ_ID
0,0,942976,Q1暴赚50亿+同环比双双翻倍！硅料龙头一季报预告亮眼，行业竞争格局不断优化？,<p><strong>财联社（上海，编辑 王舒蕾）讯</strong>，今年2月中旬以来，硅...,"[{""stocks_code"": ""sh600089""}, {""stocks_code"": ...",2022-03-28,NaN,"光伏, 新能源",NaN,"特变电工, 通威股份, 光大证券, 大全能源",NaN,"['600089.SH', '600438.SH', '601012.SH', '68830..."
1,1,942986,山东玻纤业绩预告：预计2022年一季报营业收入变动7%至19%,财联社3月28日电，山东玻纤发布2022年一季报预增公告，去年同期净利润为15251.97万...,"[{""stocks_code"": ""sh605006""}]",2022-03-28,NaN,NaN,NaN,山东玻纤,"净利润, 营业收入",['605006.SH']
2,2,942987,国联股份业绩预告：预计2022年一季报营业收入变动90.91%~100.78%,财联社3月28日电，国联股份发布2022年一季报预增公告，去年同期净利润为7801.99万元...,"[{""stocks_code"": ""sh603613""}]",2022-03-28,NaN,NaN,NaN,国联股份,"净利润, 营业收入",['603613.SH']
3,3,942988,山东玻纤业绩预告：预计2022年一季报归属公司股东扣非后净利润变动19%至32%,财联社3月28日电，山东玻纤发布2022年一季报预增公告，预计今年前一季度净利润为17483...,"[{""stocks_code"": ""sh605006""}]",2022-03-28,NaN,NaN,NaN,山东玻纤,净利润,['605006.SH']
4,4,942989,国联股份业绩预告：预计2022年一季报归属公司股东扣非后净利润变动83.70%~94.19%,财联社3月28日电，国联股份发布2022年一季报预增公告，预计今年前一季度净利润为14000...,"[{""stocks_code"": ""sh603613""}]",2022-03-28,NaN,NaN,NaN,国联股份,净利润,['603613.SH']
...,...,...,...,...,...,...,...,...,...,...,...,...
1063,1063,944055,东方中科：2021年度报告净利润17185.87万元，同比增长212.22%,财联社3月28日电，东方中科（002819）发布2021年度报告财务报告，公司2021年度报...,"[{""stocks_code"": ""sz002819""}]",2022-03-28,NaN,NaN,NaN,东方中科,"每股收益, 净利润, 营业收入",['002819.SZ']
1064,1064,944056,· 华商报：宝鸡秦川机床HMC80高精度卧式加工中心 亮相国际机床展览会,"<p>4月15日,为期五天的全球机床工具行业盛会---第十六届中国国际机床展览会(CIMT2...","[{""stocks_code"": ""sz000837""}]",2022-03-28,NaN,"机器人, 军工, 新能源, 工业母机, 航空发动机","工程机械, 航天, 航空","秦川机床, 机器人",NaN,['000837.SZ']
1065,1065,944057,兰石重装：科技创新助推检测服务提质增效,<p>日前，兰石重装子公司检测公司“无线应变测试系统”在高压容器残余应力检测中成功应用，得到...,"[{""stocks_code"": ""sh603169""}]",2022-03-28,NaN,NaN,NaN,兰石重装,NaN,['603169.SH']
1066,1066,944058,发生了什么？164家机构蜂拥调研海尔生物,<p>财联社3月28日电，2022年3月25日，海尔生物接受来自3W Fund Manage...,"[{""stocks_code"": ""sh688139""}]",2022-03-28,NaN,"物联网, 大数据, 智慧城市, 生物医药, 太阳能, 高校","疫苗, 铜","太阳能, 海尔生物","净资产收益, 净资产收益, 净利润",['688139.SH']
1067,1067,944059,多家机构3月28日调研主线曝光！华峰铝业获关注,<p>财联社3月28日电，2022年3月28日，华峰铝业接受来自中庚基金等18家机构的调研，...,"[{""stocks_code"": ""sh601702""}]",2022-03-28,NaN,"碳中和, 新能源","工程机械, 铝, 电池",华峰铝业,净利润,['601702.SH']

In [48]:
news0328=pd.read_csv("data_processed/新闻_20220328_JQ_ID.csv")
news0328.shape

stocks=news0328["JQ_ID"]
stocks

0       ['600089.SH', '600438.SH', '601012.SH', '68830...
1                                           ['605006.SH']
2                                           ['603613.SH']
3                                           ['605006.SH']
4                                           ['603613.SH']
                              ...
1063                                        ['002819.SZ']
1064                                        ['000837.SZ']
1065                                        ['603169.SH']
1066                                        ['688139.SH']
1067                                        ['601702.SH']
Name: JQ_ID, Length: 1068, dtype: object

In [49]:
import ast
news0328["JQ_ID"] = news0328["JQ_ID"].apply(ast.literal_eval)
news0328=news0328.explode('JQ_ID')
news0328.reset_index(drop=True, inplace=True)
news0328

,Unnamed: 0,id,title,content,stocks,new_date_column,宏观,概念,行业,公司,财务,JQ_ID
0,0,942976,Q1暴赚50亿+同环比双双翻倍！硅料龙头一季报预告亮眼，行业竞争格局不断优化？,<p><strong>财联社（上海，编辑 王舒蕾）讯</strong>，今年2月中旬以来，硅...,"[{""stocks_code"": ""sh600089""}, {""stocks_code"": ...",2022-03-28,NaN,"光伏, 新能源",NaN,"特变电工, 通威股份, 光大证券, 大全能源",NaN,600089.SH
1,0,942976,Q1暴赚50亿+同环比双双翻倍！硅料龙头一季报预告亮眼，行业竞争格局不断优化？,<p><strong>财联社（上海，编辑 王舒蕾）讯</strong>，今年2月中旬以来，硅...,"[{""stocks_code"": ""sh600089""}, {""stocks_code"": ...",2022-03-28,NaN,"光伏, 新能源",NaN,"特变电工, 通威股份, 光大证券, 大全能源",NaN,600438.SH
2,0,942976,Q1暴赚50亿+同环比双双翻倍！硅料龙头一季报预告亮眼，行业竞争格局不断优化？,<p><strong>财联社（上海，编辑 王舒蕾）讯</strong>，今年2月中旬以来，硅...,"[{""stocks_code"": ""sh600089""}, {""stocks_code"": ...",2022-03-28,NaN,"光伏, 新能源",NaN,"特变电工, 通威股份, 光大证券, 大全能源",NaN,601012.SH
3,0,942976,Q1暴赚50亿+同环比双双翻倍！硅料龙头一季报预告亮眼，行业竞争格局不断优化？,<p><strong>财联社（上海，编辑 王舒蕾）讯</strong>，今年2月中旬以来，硅...,"[{""stocks_code"": ""sh600089""}, {""stocks_code"": ...",2022-03-28,NaN,"光伏, 新能源",NaN,"特变电工, 通威股份, 光大证券, 大全能源",NaN,688303.SH
4,1,942986,山东玻纤业绩预告：预计2022年一季报营业收入变动7%至19%,财联社3月28日电，山东玻纤发布2022年一季报预增公告，去年同期净利润为15251.97万...,"[{""stocks_code"": ""sh605006""}]",2022-03-28,NaN,NaN,NaN,山东玻纤,"净利润, 营业收入",605006.SH
...,...,...,...,...,...,...,...,...,...,...,...,...
1212,1063,944055,东方中科：2021年度报告净利润17185.87万元，同比增长212.22%,财联社3月28日电，东方中科（002819）发布2021年度报告财务报告，公司2021年度报...,"[{""stocks_code"": ""sz002819""}]",2022-03-28,NaN,NaN,NaN,东方中科,"每股收益, 净利润, 营业收入",002819.SZ
1213,1064,944056,· 华商报：宝鸡秦川机床HMC80高精度卧式加工中心 亮相国际机床展览会,"<p>4月15日,为期五天的全球机床工具行业盛会---第十六届中国国际机床展览会(CIMT2...","[{""stocks_code"": ""sz000837""}]",2022-03-28,NaN,"机器人, 军工, 新能源, 工业母机, 航空发动机","工程机械, 航天, 航空","秦川机床, 机器人",NaN,000837.SZ
1214,1065,944057,兰石重装：科技创新助推检测服务提质增效,<p>日前，兰石重装子公司检测公司“无线应变测试系统”在高压容器残余应力检测中成功应用，得到...,"[{""stocks_code"": ""sh603169""}]",2022-03-28,NaN,NaN,NaN,兰石重装,NaN,603169.SH
1215,1066,944058,发生了什么？164家机构蜂拥调研海尔生物,<p>财联社3月28日电，2022年3月25日，海尔生物接受来自3W Fund Manage...,"[{""stocks_code"": ""sh688139""}]",2022-03-28,NaN,"物联网, 大数据, 智慧城市, 生物医药, 太阳能, 高校","疫苗, 铜","太阳能, 海尔生物","净资产收益, 净资产收益, 净利润",688139.SH
1216,1067,944059,多家机构3月28日调研主线曝光！华峰铝业获关注,<p>财联社3月28日电，2022年3月28日，华峰铝业接受来自中庚基金等18家机构的调研，...,"[{""stocks_code"": ""sh601702""}]",2022-03-28,NaN,"碳中和, 新能源","工程机械, 铝, 电池",华峰铝业,净利润,601702.SH

In [50]:
import tushare as ts
#使用tushare获取行情数据
ts.set_token('d689cb3c1d8c8a618e49ca0bb64f4d6de2f70e28ab5f76a867b31ac7')
pro = ts.pro_api()

In [63]:
stock_list=','.join(news0328["JQ_ID"][:1000].values)
stock_list
result=pro.daily(ts_code=stock_list, start_date='20220328', end_date='20220328')

# Node数据集构造

In [143]:
import os
import ast
import tushare as ts
# 创建一个空的DataFrame
dataframe = pd.DataFrame()



#定义节点处理函数
def node_process(folder_in,folder_out):
    # 获取文件夹中的所有CSV文件
    csv_files = [file for file in os.listdir(folder_in) if file.endswith('.csv')]
    for file in csv_files:
        #将股票代码转换为JQID
        # 读取CSV文件
        # 读取CSV文件
        df = pd.read_csv(os.path.join(folder_in,file),encoding='utf-8')
        # 对每一行应用处理函数，并将结果写入新的列中
        df['JQ_ID'] = df["stocks"].apply(extract_stock_codes)
        df['JQ_ID'] = df['JQ_ID'].apply(lambda x: list(map(normalize_code, x)))
        
        #提取节点
        
        #df['JQ_ID'].apply(ast.literal_eval)
        df=df.explode('JQ_ID')
        date=df["new_date_column"].iloc[1].replace("-","")
        print(date)        
        # 使用tushare补充节点特征X
        #使用tushare获取行情数据
        ts.set_token('d689cb3c1d8c8a618e49ca0bb64f4d6de2f70e28ab5f76a867b31ac7')
        pro = ts.pro_api()
        stock_list1=','.join(df["JQ_ID"][:1000].values)
        stock_list2=','.join(df["JQ_ID"][1000:2000].values)
        stock_list3=','.join(df["JQ_ID"][2000:3000].values)
        result1=pro.daily(ts_code=stock_list1, start_date=date, end_date=date)
        result2=pro.daily(ts_code=stock_list2, start_date=date, end_date=date)
        result3=pro.daily(ts_code=stock_list3, start_date=date, end_date=date)
        result=pd.concat([result1, result2,result3], ignore_index=True)
        #为节点赋y值
        result['label'] = (result['change'] > 0).astype(int)
        # 将结果写入新的CSV文件
        #print(df.columns)
        result.to_csv(os.path.join(folder_out,file), index=False)
    
# 指定文件夹路径
node_process("data_raw","data_processed")

20220327
20220328
20220329
20220330
20220331
20220402
20220404
20220405
20220406
20220407
20220408
20220409
20220410
20220411
20220412
20220413
20220414
20220415
20220416
20220417
20220419
20220421
20220422
20220423
20220424
20220425
20220426
20220427
20220428
20220429
20220430
20220501
20220502
20220503
20220504
20220505
20220506
20220507
20220508
20220509
20220510
20220511
20220512
20220513
20220514
20220515
20220516
20220518
20220519
20220520
20220521
20220522
20220523
20220524
20220525
20220526
20220527
20220528
20220529
20220601
20220602
20220603
20220604
20220605
20220606
20220607
20220608
20220609
20220610
20220611
20220612
20220613
20220614
20220615
20220616
20220618
20220619
20220620
20220621
20220622
20220623
20220624
20220625
20220626
20220627
20220628
20220629
20220630
20220701
20220702
20220703

# Edge数据集构造

In [1]:
import os
import ast
import tushare as ts
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv("data_raw/新闻_20220328.csv")
df['JQ_ID'] = df["stocks"].apply(extract_stock_codes)
df['JQ_ID'] = df['JQ_ID'].apply(lambda x: list(map(normalize_code, x)))
df.head()

,Unnamed: 0,id,title,content,stocks,new_date_column,宏观,概念,行业,公司,财务,JQ_ID
0,0,942976,Q1暴赚50亿+同环比双双翻倍！硅料龙头一季报预告亮眼，行业竞争格局不断优化？,<p><strong>财联社（上海，编辑 王舒蕾）讯</strong>，今年2月中旬以来，硅...,"[{""stocks_code"": ""sh600089""}, {""stocks_code"": ...",2022-03-28,NaN,"光伏, 新能源",NaN,"特变电工, 通威股份, 光大证券, 大全能源",NaN,"[600089.SH, 600438.SH, 601012.SH, 688303.SH]"
1,1,942986,山东玻纤业绩预告：预计2022年一季报营业收入变动7%至19%,财联社3月28日电，山东玻纤发布2022年一季报预增公告，去年同期净利润为15251.97万...,"[{""stocks_code"": ""sh605006""}]",2022-03-28,NaN,NaN,NaN,山东玻纤,"净利润, 营业收入",[605006.SH]
2,2,942987,国联股份业绩预告：预计2022年一季报营业收入变动90.91%~100.78%,财联社3月28日电，国联股份发布2022年一季报预增公告，去年同期净利润为7801.99万元...,"[{""stocks_code"": ""sh603613""}]",2022-03-28,NaN,NaN,NaN,国联股份,"净利润, 营业收入",[603613.SH]
3,3,942988,山东玻纤业绩预告：预计2022年一季报归属公司股东扣非后净利润变动19%至32%,财联社3月28日电，山东玻纤发布2022年一季报预增公告，预计今年前一季度净利润为17483...,"[{""stocks_code"": ""sh605006""}]",2022-03-28,NaN,NaN,NaN,山东玻纤,净利润,[605006.SH]
4,4,942989,国联股份业绩预告：预计2022年一季报归属公司股东扣非后净利润变动83.70%~94.19%,财联社3月28日电，国联股份发布2022年一季报预增公告，预计今年前一季度净利润为14000...,"[{""stocks_code"": ""sh603613""}]",2022-03-28,NaN,NaN,NaN,国联股份,净利润,[603613.SH]

In [9]:
df2=df[df['JQ_ID'].apply(lambda x: isinstance(x, list) and len(x) > 1)]

In [16]:
from itertools import combinations
combinations_list = list(combinations(df2['JQ_ID'][0], 2))
new_data = {'JQ_ID': combinations_list}
new_df = pd.DataFrame(new_data)

In [17]:
new_df

                    JQ_ID
0  (600089.SH, 600438.SH)
1  (600089.SH, 601012.SH)
2  (600089.SH, 688303.SH)
3  (600438.SH, 601012.SH)
4  (600438.SH, 688303.SH)
5  (601012.SH, 688303.SH)

In [23]:
# 将每一行的元素转换为组合形式
def generate_combinations(row):
    combinations_list = list(combinations(row, 2))
    return combinations_list

# 对每一行都进行组合操作
df['Combinations'] = df2['JQ_ID'].apply(generate_combinations)

# 创建新的DataFrame
new_data = {'JQ_ID': [item for sublist in df2['Combinations'] for item in sublist]}
new_df = pd.DataFrame(new_data)

In [24]:
new_df

                      JQ_ID
0    (600089.SH, 600438.SH)
1    (600089.SH, 601012.SH)
2    (600089.SH, 688303.SH)
3    (600438.SH, 601012.SH)
4    (600438.SH, 688303.SH)
..                      ...
589  (002594.SZ, 300037.SZ)
590  (002594.SZ, 300750.SZ)
591  (300037.SZ, 300750.SZ)
592  (601166.SH, 601229.SH)
593  (688336.SH, 688336.SH)

[594 rows x 1 columns]

In [25]:
new_df['stock1'] = new_df['JQ_ID'].str[0]
new_df['stock2'] = new_df['JQ_ID'].str[1]

# 删除原始的JQ_ID列
new_df.drop('JQ_ID', axis=1, inplace=True)

In [26]:
new_df

        stock1     stock2
0    600089.SH  600438.SH
1    600089.SH  601012.SH
2    600089.SH  688303.SH
3    600438.SH  601012.SH
4    600438.SH  688303.SH
..         ...        ...
589  002594.SZ  300037.SZ
590  002594.SZ  300750.SZ
591  300037.SZ  300750.SZ
592  601166.SH  601229.SH
593  688336.SH  688336.SH

[594 rows x 2 columns]

In [22]:
df2["Combinations"][0]

[('600089.SH', '600438.SH'),
 ('600089.SH', '601012.SH'),
 ('600089.SH', '688303.SH'),
 ('600438.SH', '601012.SH'),
 ('600438.SH', '688303.SH'),
 ('601012.SH', '688303.SH')]

In [29]:
#定义边处理函数
def edge_process(folder_in,folder_out):
    # 获取文件夹中的所有CSV文件
    csv_files = [file for file in os.listdir(folder_in) if file.endswith('.csv')]
    for file in csv_files:
        #将股票代码转换为JQID
        # 读取CSV文件
        # 读取CSV文件
        df = pd.read_csv(os.path.join(folder_in,file),encoding='utf-8')
        # 对每一行应用处理函数，并将结果写入新的列中
        df['JQ_ID'] = df["stocks"].apply(extract_stock_codes)
        df['JQ_ID'] = df['JQ_ID'].apply(lambda x: list(map(normalize_code, x)))
        
        #提取节点
        
        #df['JQ_ID'].apply(ast.literal_eval)
        df=df.explode('JQ_ID')
        date=df["new_date_column"].iloc[1].replace("-","")
        print(date)        
        
        # 对每一行都进行组合操作
        df['Combinations'] = df2['JQ_ID'].apply(generate_combinations)

        # 创建新的DataFrame
        new_data = {'JQ_ID': [item for sublist in df2['Combinations'] for item in sublist]}
        new_df = pd.DataFrame(new_data)
        new_df['stock1'] = new_df['JQ_ID'].str[0]
        new_df['stock2'] = new_df['JQ_ID'].str[1]

        # 删除原始的JQ_ID列
        new_df.drop('JQ_ID', axis=1, inplace=True)
        
        # 将结果写入新的CSV文件
        #print(df.columns)
        new_df.to_csv(os.path.join(folder_out,file), index=False)
    
# 指定文件夹路径
edge_process("data_raw","edge")

20220327
20220328
20220329
20220330
20220331
20220402
20220404
20220405
20220406
20220407
20220408
20220409
20220410
20220411
20220412
20220413
20220414
20220415
20220416
20220417
20220419
20220421
20220422
20220423
20220424
20220425
20220426
20220427
20220428
20220429
20220430
20220501
20220502
20220503
20220504
20220505
20220506
20220507
20220508
20220509
20220510
20220511
20220512
20220513
20220514
20220515
20220516
20220518
20220519
20220520
20220521
20220522
20220523
20220524
20220525
20220526
20220527
20220528
20220529
20220601
20220602
20220603
20220604
20220605
20220606
20220607
20220608
20220609
20220610
20220611
20220612
20220613
20220614
20220615
20220616
20220618
20220619
20220620
20220621
20220622
20220623
20220624
20220625
20220626
20220627
20220628
20220629
20220630
20220701
20220702
20220703

# Edge feature